# Copyright (c) 2026 sbula. All rights reserved.
# Licensed under the Apache License, Version 2.0. See LICENSE file in the project root.

"""Context YAML inferrer — auto-generates context.yaml for directories missing one.

When the TopologyGraph encounters a source directory without a context.yaml,
ContextInferrer uses a LanguageAnalyzer to extract what it can from the code
and writes a best-effort context.yaml with an AUTO-GENERATED header.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from io import StringIO
from pathlib import Path  # noqa: TC003 — used at runtime, not just type hints

from ruamel.yaml import YAML

from specweaver.context.analyzers import AnalyzerFactory

logger = logging.getLogger(__name__)

# Level inference: given a parent's level, what level should the child be?
_CHILD_LEVEL: dict[str, str] = {
    "system": "service",
    "service": "module",
    "meta-module": "module",
    "module": "sub-module",
    "sub-module": "sub-module",
}

_AUTO_HEADER = (
    "# AUTO-GENERATED — potentially incomplete. Review and update.\n"
    "# Generated by SpecWeaver ContextInferrer from source code analysis.\n"
    "# Fields 'constraints' and 'operational' cannot be inferred and need manual input.\n"
)


@dataclass
class InferredNode:
    """Data extracted from code analysis for a single directory."""

    name: str
    level: str
    purpose: str
    archetype: str
    imports: list[str] = field(default_factory=list)
    exposes: list[str] = field(default_factory=list)
    yaml_path: Path | None = None


@dataclass
class InferenceResult:
    """Result of attempting to infer and write a context.yaml."""

    node: InferredNode | None
    was_generated: bool
    warnings: list[str] = field(default_factory=list)


class ContextInferrer:
    """Auto-generate context.yaml files from source code analysis.

    Uses AnalyzerFactory to detect the language and extract fields.
    Writes the generated file to disk with an AUTO-GENERATED header.
    """

    def infer_and_write(
        self,
        directory: Path,
        parent_level: str | None = None,
    ) -> InferenceResult:
        """Attempt to infer and write a context.yaml for the given directory.

        Args:
            directory: The directory to analyze.
            parent_level: The level of the parent boundary (used to infer child level).

        Returns:
            InferenceResult with the generated node and any warnings.
        """
        # Skip if context.yaml already exists
        ctx_file = directory / "context.yaml"
        if ctx_file.is_file():
            logger.debug(
                "ContextInferrer: skipping '%s' — context.yaml already exists", directory.name
            )
            return InferenceResult(node=None, was_generated=False)

        # Skip if no analyzable source files
        analyzer = AnalyzerFactory.for_directory(directory)
        if analyzer is None:
            logger.debug(
                "ContextInferrer: skipping '%s' — no analyzable source files", directory.name
            )
            return InferenceResult(node=None, was_generated=False)

        # Extract what we can
        name = directory.name
        purpose = analyzer.extract_purpose(directory) or "TODO — no docstring found."
        imports = analyzer.extract_imports(directory)
        exposes = analyzer.extract_public_symbols(directory)
        archetype = analyzer.infer_archetype(directory)
        level = _CHILD_LEVEL.get(parent_level, "module") if parent_level else "module"

        node = InferredNode(
            name=name,
            level=level,
            purpose=purpose,
            archetype=archetype,
            imports=imports,
            exposes=exposes,
            yaml_path=ctx_file,
        )

        # Build YAML content
        data: dict[str, object] = {
            "name": name,
            "level": level,
            "purpose": purpose,
            "archetype": archetype,
        }
        if exposes:
            data["exposes"] = exposes

        yaml = YAML()
        yaml.default_flow_style = False
        buf = StringIO()
        yaml.dump(data, buf)
        content = _AUTO_HEADER + "\n" + buf.getvalue()

        # Write to disk
        ctx_file.write_text(content, encoding="utf-8")
        logger.info(
            "ContextInferrer: generated context.yaml for '%s' (level=%s, archetype=%s, exports=%d)",
            name,
            level,
            archetype,
            len(exposes),
        )

        warnings = [
            f"Auto-generated context.yaml for '{name}' at {ctx_file}. "
            "Please review — constraints and operational fields are missing.",
        ]
        for w in warnings:
            logger.warning(w)

        return InferenceResult(
            node=node,
            was_generated=True,
            warnings=warnings,
        )
