# Copyright (c) 2026 sbula. All rights reserved.
# Licensed under the Apache License, Version 2.0. See LICENSE file in the project root.

"""CLI commands for Git hooks deployment: sw hooks install."""

from __future__ import annotations

import logging
import stat
import sys

import typer

from specweaver.interfaces.cli import _core
from specweaver.workspace.project.discovery import resolve_project_path

logger = logging.getLogger(__name__)

hooks_app = typer.Typer(
    name="hooks",
    help="Git hook installation and management.",
    no_args_is_help=True,
)
_core.app.add_typer(hooks_app, name="hooks")

HOOK_TEMPLATE = """#!/usr/bin/env bash
# AUTO-GENERATED BY SPECWEAVER
# Do not edit this file manually.

# Enforce SpecWeaver AST/Spec contract drift detection.
# If this fails, review the output and either fix the code or the Spec.md contract.

echo ">>> SpecWeaver: Running Bi-Directional Spec Rot Interceptor (Feature 3.23) <<<"

"{python_exec}" -m specweaver.interfaces.cli.main drift check-rot --staged
exit_code=$?

if [ $exit_code -eq 42 ]; then
    echo ""
    echo "================================================================"
    echo "ERROR: SpecWeaver detected structural drift between Spec and Code!"
    echo "Fix the mismatch to proceed with this commit."
    echo "================================================================"
    exit 1
elif [ $exit_code -ne 0 ]; then
    echo ""
    echo "================================================================"
    echo "ERROR: The SpecWeaver pipeline crashed ($exit_code)."
    echo "Please check your python environment or the stack trace above."
    echo "================================================================"
    exit 1
fi
"""


@hooks_app.command("install")
def hooks_install(
    pre_commit: bool = typer.Option(
        True,
        "--pre-commit/--no-pre-commit",
        help="Install the pre-commit hook (Spec Rot Interceptor).",
    ),
    project: str | None = typer.Option(
        None,
        "--project",
        "-p",
        help="Path to the target project directory.",
    ),
) -> None:
    """Install git hooks for the current repository."""
    try:
        project_path = resolve_project_path(project)
        logger.debug(f"Resolved project path: {project_path}")
    except (FileNotFoundError, NotADirectoryError) as exc:
        logger.error(f"Project path resolution failed: {exc}")
        _core.console.print(f"[red]Error:[/red] {exc}")
        raise typer.Exit(code=1) from exc

    git_dir = project_path / ".git"
    if not git_dir.exists() or not git_dir.is_dir():
        logger.error(f"Target is not a git repository: {git_dir}")
        _core.console.print(
            "[red]Error:[/red] Target project is not a git repository (missing .git directory)."
        )
        raise typer.Exit(code=1)

    hooks_dir = git_dir / "hooks"
    logger.debug(f"Ensuring hooks directory exists: {hooks_dir}")
    hooks_dir.mkdir(exist_ok=True)

    if pre_commit:
        hook_path = hooks_dir / "pre-commit"
        python_exec = str(sys.executable)

        hook_content = HOOK_TEMPLATE.format(python_exec=python_exec)

        # Write the file
        logger.debug(f"Writing hook to {hook_path}")
        hook_path.write_text(hook_content, encoding="utf-8")

        # Apply execution permissions (chmod +x)
        st = hook_path.stat()
        hook_path.chmod(st.st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)

        logger.info(f"Successfully installed pre-commit hook at {hook_path}")
        _core.console.print(
            "[green]Success: SpecWeaver pre-commit hook installed successfully.[/green]"
        )
    else:
        logger.info("Skip pre-commit hook installation per options.")
