# Copyright (c) 2026 sbula. All rights reserved.
# Licensed under the Apache License, Version 2.0. See LICENSE file in the project root.

"""DependencyHasher — Merkle-tree hashing for cache state.

Replaces shallow file hashing with "Dependency Hashing". Uses the LanguageAnalyzer
components to deeply extract imports, generating a robust structural signature.
"""

from __future__ import annotations

import hashlib
import logging
from pathlib import Path
from typing import TYPE_CHECKING, cast

from specweaver.commons import json

if TYPE_CHECKING:
    from specweaver.workspace.context.analyzer_protocols import AnalyzerFactoryProtocol
logger = logging.getLogger(__name__)


def _ensure_gitignore(project_root: Path) -> None:
    """Walk upwards to find the exact .git folder, then append /.specweaver/ to .gitignore.

    This explicitly guarantees that the Semantic Topology Cache and other internal
    artifacts generated by the Agent Loop are not accidentally committed to version control.
    """
    current_dir = list(project_root.resolve().parents)
    current_dir.insert(0, project_root.resolve())

    git_home = None
    for directory in current_dir:
        if (directory / ".git").is_dir():
            git_home = directory
            break

    if git_home is None:
        logger.debug("Failed to locate .git repository root. Skipping gitignore enforcement.")
        return

    gitignore_path = git_home / ".gitignore"
    entry = "/.specweaver/\n"

    try:
        if not gitignore_path.exists():
            gitignore_path.write_text(entry, encoding="utf-8")
            logger.info("Created .gitignore at repository root and injected /.specweaver/")
            return

        contents = gitignore_path.read_text(encoding="utf-8")
        lines = contents.splitlines()

        if "/.specweaver/" not in lines:
            if not contents.endswith("\n") and len(contents) > 0:
                with gitignore_path.open("a", encoding="utf-8") as f:
                    f.write("\n" + entry)
            else:
                with gitignore_path.open("a", encoding="utf-8") as f:
                    f.write(entry)
            logger.info("Injected /.specweaver/ into existing .gitignore")

    except Exception as e:
        logger.warning(f"Failed to ensure .specweaver/ is ignored by Git: {e}")


class DependencyHasher:
    """Computes semantic merkle-tree hashes for topology boundaries."""

    def __init__(self, project_root: Path, analyzer_factory: AnalyzerFactoryProtocol):
        self.project_root = project_root.resolve()
        self.cache_dir = self.project_root / ".specweaver"
        self.cache_path = self.cache_dir / "topology.cache.json"
        self.analyzer_factory = analyzer_factory

    @staticmethod
    def _hash_file(filepath: Path) -> str:
        """Compute SHA-256 for a single file."""
        hasher = hashlib.sha256()
        try:
            with filepath.open("rb") as f:
                for chunk in iter(lambda: f.read(65536), b""):
                    hasher.update(chunk)
            return hasher.hexdigest()
        except OSError as e:
            logger.debug(f"DependencyHasher failed to read {filepath}: {e}")
            return ""

    def _hash_directory(self, directory: Path) -> dict[str, str]:  # noqa: C901
        """Compute the semantic hash payload for a specific boundary directory."""
        import os

        file_hashes = {}
        skip_dirs = {".git"}
        binary_patterns: list[str] = []

        for analyzer in self.analyzer_factory.get_all_analyzers():
            for ign in analyzer.get_default_directory_ignores():
                skip_dirs.add(ign.rstrip("/"))
            binary_patterns.extend(analyzer.get_binary_ignore_patterns())

        ignore_file = self.project_root / ".specweaverignore"
        if ignore_file.is_file():
            binary_patterns.extend(ignore_file.read_text(encoding="utf-8").splitlines())

        spec = None
        if binary_patterns:
            try:
                import pathspec

                spec = pathspec.PathSpec.from_lines("gitignore", binary_patterns)
            except ImportError:
                logger.warning("pathspec not installed; ignoring binary and .specweaverignore patterns")

        for root, dirs, files in os.walk(directory):
            dirs[:] = [d for d in dirs if d not in skip_dirs and not d.startswith(".")]

            root_path = Path(root)
            for f in files:
                if f.startswith("."):
                    continue

                filepath = root_path / f
                if filepath.is_symlink() or not filepath.is_file():
                    continue

                try:
                    rel_to_proj = filepath.relative_to(self.project_root).as_posix()
                except ValueError:
                    rel_to_proj = filepath.as_posix()

                if spec and spec.match_file(rel_to_proj):
                    continue

                h = self._hash_file(filepath)
                if h:
                    try:
                        rel_path = filepath.relative_to(directory).as_posix()
                    except ValueError:
                        rel_path = filepath.as_posix()
                    file_hashes[rel_path] = h

        local_analyzer = self.analyzer_factory.for_directory(directory)
        dependencies = local_analyzer.extract_imports(directory) if local_analyzer else []

        payload = {"files": file_hashes, "dependencies": sorted(dependencies)}

        rendered = json.dumps(payload, sort_keys=True)
        merkle_root = hashlib.sha256(rendered.encode("utf-8")).hexdigest()

        return {"merkle_root": merkle_root, "rendered_payload": rendered}

    def load_cache(self) -> dict[str, dict[str, str]]:
        """Read the existing semantic cache from disk."""
        if not self.cache_path.exists():
            return {}
        try:
            raw = self.cache_path.read_text(encoding="utf-8")
            return cast("dict[str, dict[str, str]]", json.loads(raw))
        except Exception as e:
            logger.warning(f"Failed to load semantic cache {self.cache_path}: {e}")
            return {}

    def save_cache(self, cache_state: dict[str, dict[str, str]] | None = None) -> None:
        """Write the active semantic state securely to disk."""
        if cache_state is None:
            manifests = list(self.project_root.rglob("context.yaml"))
            cache_state = self.compute_hashes(manifests)

        try:
            self.cache_dir.mkdir(parents=True, exist_ok=True)
            _ensure_gitignore(self.project_root)
            payload = json.dumps(cache_state, sort_keys=True)
            self.cache_path.write_text(payload, encoding="utf-8")
        except Exception as e:
            logger.debug(f"Failed to persist topology cache: {e}")

    def compute_hashes(self, manifests: list[Path]) -> dict[str, dict[str, str]]:
        """Compute semantic hashes across all active manifests and prune orphans.

        Loads active cache, processes each context.yaml boundary, drops deleted bounds,
        and returns the consolidated Merkle state.
        """
        # Used for structural diffing eventually: active_cache = self.load_cache()
        new_state = {}

        for manifest in manifests:
            directory = manifest.parent
            # Convert physical path to string key for JSON compatibility
            bound_key = directory.relative_to(self.project_root).as_posix()

            # Recalculating hash (In a true incremental crawl, we'd check mtime first,
            # but compute logic runs here)
            new_state[bound_key] = self._hash_directory(directory)

        return new_state
