# Copyright (c) 2026 sbula. All rights reserved.
# Licensed under the Apache License, Version 2.0. See LICENSE file in the project root.

"""DependencyHasher — Merkle-tree hashing for cache state.

Replaces shallow file hashing with "Dependency Hashing". Uses the LanguageAnalyzer
components to deeply extract imports, generating a robust structural signature.
"""

from __future__ import annotations

import hashlib
import logging
from typing import cast
from pathlib import Path  # noqa: TC003

from specweaver.commons import json
from specweaver.workspace.context.analyzers import AnalyzerFactory

logger = logging.getLogger(__name__)


def _ensure_gitignore(project_root: Path) -> None:
    """Walk upwards to find the exact .git folder, then append /.specweaver/ to .gitignore.

    This explicitly guarantees that the Semantic Topology Cache and other internal
    artifacts generated by the Agent Loop are not accidentally committed to version control.
    """
    current_dir = list(project_root.resolve().parents)
    current_dir.insert(0, project_root.resolve())

    git_home = None
    for directory in current_dir:
        if (directory / ".git").is_dir():
            git_home = directory
            break

    if git_home is None:
        logger.debug("Failed to locate .git repository root. Skipping gitignore enforcement.")
        return

    gitignore_path = git_home / ".gitignore"
    entry = "/.specweaver/\n"

    try:
        if not gitignore_path.exists():
            gitignore_path.write_text(entry, encoding="utf-8")
            logger.info("Created .gitignore at repository root and injected /.specweaver/")
            return

        contents = gitignore_path.read_text(encoding="utf-8")
        lines = contents.splitlines()

        if "/.specweaver/" not in lines:
            if not contents.endswith("\n") and len(contents) > 0:
                with gitignore_path.open("a", encoding="utf-8") as f:
                    f.write("\n" + entry)
            else:
                with gitignore_path.open("a", encoding="utf-8") as f:
                    f.write(entry)
            logger.info("Injected /.specweaver/ into existing .gitignore")

    except Exception as e:
        logger.warning(f"Failed to ensure .specweaver/ is ignored by Git: {e}")


class DependencyHasher:
    """Computes semantic merkle-tree hashes for topology boundaries."""

    def __init__(self, project_root: Path):
        self.project_root = project_root.resolve()
        self.cache_dir = self.project_root / ".specweaver"
        self.cache_path = self.cache_dir / "topology.cache.json"

    @staticmethod
    def _hash_file(filepath: Path) -> str:
        """Compute SHA-256 for a single file."""
        hasher = hashlib.sha256()
        try:
            with filepath.open("rb") as f:
                for chunk in iter(lambda: f.read(65536), b""):
                    hasher.update(chunk)
            return hasher.hexdigest()
        except OSError as e:
            logger.debug(f"DependencyHasher failed to read {filepath}: {e}")
            return ""

    def _hash_directory(self, directory: Path) -> dict[str, str]:
        """Compute the semantic hash payload for a specific boundary directory."""
        file_hashes = {}
        for filepath in sorted(directory.rglob("*")):
            if filepath.is_file() and not filepath.is_symlink() and not any(part.startswith(".") for part in filepath.parts):
                h = self._hash_file(filepath)
                if h:
                    rel_path = filepath.relative_to(directory).as_posix()
                    file_hashes[rel_path] = h

        analyzer = AnalyzerFactory.for_directory(directory)
        dependencies = analyzer.extract_imports(directory) if analyzer else []

        payload = {
            "files": file_hashes,
            "dependencies": sorted(dependencies)
        }

        rendered = json.dumps(payload, sort_keys=True)
        merkle_root = hashlib.sha256(rendered.encode("utf-8")).hexdigest()

        return {
            "merkle_root": merkle_root,
            "rendered_payload": rendered
        }

    def load_cache(self) -> dict[str, dict[str, str]]:
        """Read the existing semantic cache from disk."""
        if not self.cache_path.exists():
            return {}
        try:
            raw = self.cache_path.read_text(encoding="utf-8")
            return cast(dict[str, dict[str, str]], json.loads(raw))
        except Exception as e:
            logger.warning(f"Failed to load semantic cache {self.cache_path}: {e}")
            return {}

    def save_cache(self, cache_state: dict[str, dict[str, str]]) -> None:
        """Write the active semantic state securely to disk."""
        try:
            self.cache_dir.mkdir(parents=True, exist_ok=True)
            _ensure_gitignore(self.project_root)
            payload = json.dumps(cache_state, sort_keys=True)
            self.cache_path.write_text(payload, encoding="utf-8")
        except Exception as e:
            logger.debug(f"Failed to persist topology cache: {e}")

    def compute_hashes(self, manifests: list[Path]) -> dict[str, dict[str, str]]:
        """Compute semantic hashes across all active manifests and prune orphans.

        Loads active cache, processes each context.yaml boundary, drops deleted bounds,
        and returns the consolidated Merkle state.
        """
        # Used for structural diffing eventually: active_cache = self.load_cache()
        new_state = {}

        for manifest in manifests:
            directory = manifest.parent
            # Convert physical path to string key for JSON compatibility
            bound_key = directory.relative_to(self.project_root).as_posix()

            # Recalculating hash (In a true incremental crawl, we'd check mtime first,
            # but compute logic runs here)
            new_state[bound_key] = self._hash_directory(directory)

        # Write exact bounds (orphans missing from `manifests` are inherently dropped)
        self.save_cache(new_state)
        return new_state
