# mypy: ignore-errors
from typing import Protocol

import networkx as nx

from specweaver.graph.core.engine.models import GraphEdge, GraphNode


class NodeNotFoundError(Exception):
    """Raised when an operation targets a semantic hash that does not exist."""

    pass


class GraphEngineProtocol(Protocol):
    def upsert_node(self, node: GraphNode) -> None: ...
    def upsert_edge(self, edge: GraphEdge) -> None: ...
    def remove_node(self, semantic_hash: str) -> None: ...
    def remove_edge(self, source_hash: str, target_hash: str) -> None: ...
    def get_nodes_for_file(self, file_id: str) -> set[str]: ...
    def get_edges_involving(self, semantic_hashes: set[str]) -> set[tuple[str, str]]: ...
    def export_semantic_digraph(self) -> nx.DiGraph: ...  # type: ignore[type-arg]
    def load_semantic_digraph(self, semantic_digraph: nx.DiGraph) -> None: ...  # type: ignore[type-arg]
    def extract_subgraph(self, start_hash: str, depth: int) -> nx.DiGraph: ...  # type: ignore[type-arg]
    def to_graphml_string(self) -> str: ...
    def clear_cache(self) -> None: ...
