exclude = []
source_roots = [
    ".",
]

[[modules]]
path = "src.specweaver.api"

[[modules]]
path = "src.specweaver.cli"

[[modules]]
path = "src.specweaver.config"
depends_on = []

[[modules]]
path = "src.specweaver.context"
depends_on = []

[[modules]]
path = "src.specweaver.graph"
depends_on = []

[[modules]]
path = "src.specweaver.llm"
depends_on = [
]

[[modules]]
path = "src.specweaver.logging"
depends_on = []

[[modules]]
path = "src.specweaver.project"
depends_on = []

[[modules]]
path = "src.specweaver.standards"
depends_on = []

[[interfaces]]
expose = []
from = [
    "src.specweaver.llm",
]
