# Copyright (c) 2026 sbula. All rights reserved.
# Licensed under the Apache License, Version 2.0. See LICENSE file in the project root.

"""A polyglot monorepo is read for its source, not for what its build tools left behind.

Proves: INT-US-05 P-2

Every file discovery reaches an LLM's context window eventually, and a monorepo carries far more
generated bytes than authored ones — `node_modules`, `target`, `build`, `.venv`, minified bundles.
Pulling those in does not merely waste budget; it teaches the standards scanner conventions from
vendored code the project never wrote.

The assertion is deliberately two-sided. "No `node_modules` file was returned" is satisfied by a
discovery that returns nothing at all, so the real source files must be present in the same breath.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import pytest

from specweaver.assurance.standards.discovery import discover_files
from specweaver.workspace.analyzers.factory import AnalyzerFactory

if TYPE_CHECKING:
    from pathlib import Path

#: Authored source, in three languages — this is what a scan is for.
_AUTHORED = {
    "services/billing/ledger.py": "def post(a: int) -> int:\n    return a\n",
    "services/web/app.ts": "export const app = () => 1;\n",
    "services/api/Handler.java": "package api;\npublic class Handler {}\n",
}

#: What the build tools left. Every one of these is a real path shape from a real ecosystem.
_GENERATED = {
    "node_modules/left-pad/index.js": "module.exports = 1;\n",
    "services/web/node_modules/dep/index.js": "module.exports = 2;\n",
    "target/classes/api/Handler.class": "\x00\x00compiled\n",
    "services/api/build/generated/Stub.java": "package api;\npublic class Stub {}\n",
    ".venv/lib/python3.14/site-packages/vendored/mod.py": "VENDORED = True\n",
}


@pytest.fixture
def monorepo(tmp_path: Path) -> Path:
    for rel, body in {**_AUTHORED, **_GENERATED}.items():
        f = tmp_path / rel
        f.parent.mkdir(parents=True, exist_ok=True)
        f.write_text(body, encoding="utf-8")
    return tmp_path


def test_authored_source_is_found_and_build_output_is_not(monorepo: Path) -> None:
    """Both halves matter: a discovery returning nothing would satisfy either one alone."""
    found = discover_files(monorepo, AnalyzerFactory)
    relative = {p.relative_to(monorepo).as_posix() for p in found}

    missing = set(_AUTHORED) - relative
    assert not missing, (
        f"authored source was skipped, so the scan sees a smaller project: {missing}"
    )

    leaked = set(_GENERATED) & relative
    assert not leaked, (
        f"build output reached the discovery set and would reach the token context with it: {leaked}"
    )


def test_a_project_ignore_file_is_honoured(monorepo: Path) -> None:
    """`.specweaverignore` is how a project excludes what the built-in rules cannot know about.

    Asserted separately from the defaults above, because a discovery that hardcoded the ecosystem
    directories would pass the first test while ignoring the project's own wishes entirely.
    """
    (monorepo / "services" / "vendor_dump.py").write_text("LEGACY = 1\n", encoding="utf-8")
    before = {p.relative_to(monorepo).as_posix() for p in discover_files(monorepo, AnalyzerFactory)}
    assert "services/vendor_dump.py" in before, (
        "fixture is wrong — the file must start out included"
    )

    (monorepo / ".specweaverignore").write_text("services/vendor_dump.py\n", encoding="utf-8")

    after = {p.relative_to(monorepo).as_posix() for p in discover_files(monorepo, AnalyzerFactory)}
    assert "services/vendor_dump.py" not in after, (
        "the project asked for a path to be excluded and the scan took it anyway"
    )
    assert "services/billing/ledger.py" in after, "the ignore file excluded more than it named"
