"""Init monolith schema

Revision ID: 037b85034bb0
Revises:
Create Date: 2026-05-02 14:21:41.946055

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import specweaver.core.config.database

# revision identifiers, used by Alembic.
revision: str = "037b85034bb0"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("active_state") as batch_op:
        batch_op.alter_column("key", existing_type=sa.TEXT(), type_=sa.String(), nullable=False
    )
    with op.batch_alter_table("active_state") as batch_op:
        batch_op.alter_column("value", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False
    )
    with op.batch_alter_table("artifact_events") as batch_op:
        batch_op.alter_column("id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
    )
    with op.batch_alter_table("artifact_events") as batch_op:
        batch_op.alter_column("artifact_id",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    with op.batch_alter_table("artifact_events") as batch_op:
        batch_op.alter_column("parent_id",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    with op.batch_alter_table("artifact_events") as batch_op:
        batch_op.alter_column("run_id",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    with op.batch_alter_table("artifact_events") as batch_op:
        batch_op.alter_column("event_type",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    with op.batch_alter_table("artifact_events") as batch_op:
        batch_op.alter_column("timestamp",
        existing_type=sa.TEXT(),
        type_=specweaver.core.config.database.StrictISODateTime(),
        existing_nullable=False,
    )
    with op.batch_alter_table("artifact_events") as batch_op:
        batch_op.alter_column("model_id",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
        existing_server_default=sa.text("'unknown'"),
    )
    op.drop_index(op.f("idx_lineage_artifact"), table_name="artifact_events")
    op.drop_index(op.f("idx_lineage_parent"), table_name="artifact_events")
    op.create_index(
        op.f("ix_artifact_events_artifact_id"), "artifact_events", ["artifact_id"], unique=False
    )
    op.create_index(
        op.f("ix_artifact_events_parent_id"), "artifact_events", ["parent_id"], unique=False
    )
    with op.batch_alter_table("llm_cost_overrides") as batch_op:
        batch_op.alter_column("model_pattern",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        nullable=False,
    )
    with op.batch_alter_table("llm_cost_overrides") as batch_op:
        batch_op.alter_column("input_cost_per_1k",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=False,
    )
    with op.batch_alter_table("llm_cost_overrides") as batch_op:
        batch_op.alter_column("output_cost_per_1k",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=False,
    )
    with op.batch_alter_table("llm_cost_overrides") as batch_op:
        batch_op.alter_column("updated_at",
        existing_type=sa.TEXT(),
        type_=specweaver.core.config.database.StrictISODateTime(),
        existing_nullable=False,
    )
    with op.batch_alter_table("llm_profiles") as batch_op:
        batch_op.alter_column("id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
    )
    with op.batch_alter_table("llm_profiles") as batch_op:
        batch_op.alter_column("name", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False
    )
    with op.batch_alter_table("llm_profiles") as batch_op:
        batch_op.alter_column("model",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
        existing_server_default=sa.text("'gemini-3-flash-preview'"),
    )
    with op.batch_alter_table("llm_profiles") as batch_op:
        batch_op.alter_column("temperature",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=False,
        existing_server_default=sa.text("(0.7)"),
    )
    with op.batch_alter_table("llm_profiles") as batch_op:
        batch_op.alter_column("response_format",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
        existing_server_default=sa.text("'text'"),
    )
    with op.batch_alter_table("llm_profiles") as batch_op:
        batch_op.alter_column("provider",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
        existing_server_default=sa.text("'gemini'"),
    )
    with op.batch_alter_table("llm_usage_log") as batch_op:
        batch_op.alter_column("id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
    )
    with op.batch_alter_table("llm_usage_log") as batch_op:
        batch_op.alter_column("timestamp",
        existing_type=sa.TEXT(),
        type_=specweaver.core.config.database.StrictISODateTime(),
        existing_nullable=False,
    )
    with op.batch_alter_table("llm_usage_log") as batch_op:
        batch_op.alter_column("project_name",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    with op.batch_alter_table("llm_usage_log") as batch_op:
        batch_op.alter_column("task_type",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    with op.batch_alter_table("llm_usage_log") as batch_op:
        batch_op.alter_column("model",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    with op.batch_alter_table("llm_usage_log") as batch_op:
        batch_op.alter_column("provider",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
        existing_server_default=sa.text("('')"),
    )
    with op.batch_alter_table("llm_usage_log") as batch_op:
        batch_op.alter_column("estimated_cost",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=False,
        existing_server_default=sa.text("(0.0)"),
    )
    with op.batch_alter_table("llm_usage_log") as batch_op:
        batch_op.alter_column("run_id",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
        existing_server_default=sa.text("('')"),
    )
    op.drop_index(op.f("idx_usage_project"), table_name="llm_usage_log")
    op.drop_index(op.f("idx_usage_task_type"), table_name="llm_usage_log")
    op.create_index(
        op.f("ix_llm_usage_log_project_name"), "llm_usage_log", ["project_name"], unique=False
    )
    op.create_index(
        op.f("ix_llm_usage_log_task_type"), "llm_usage_log", ["task_type"], unique=False
    )
    with op.batch_alter_table("project_llm_links") as batch_op:
        batch_op.alter_column("project_name",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    with op.batch_alter_table("project_llm_links") as batch_op:
        batch_op.alter_column("role",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.drop_constraint(None, "project_llm_links", type_="foreignkey")  # type: ignore[arg-type]
    with op.batch_alter_table("project_standards") as batch_op:
        batch_op.alter_column("project_name",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    with op.batch_alter_table("project_standards") as batch_op:
        batch_op.alter_column("scope",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    with op.batch_alter_table("project_standards") as batch_op:
        batch_op.alter_column("language",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    with op.batch_alter_table("project_standards") as batch_op:
        batch_op.alter_column("category",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    with op.batch_alter_table("project_standards") as batch_op:
        batch_op.alter_column("data",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    with op.batch_alter_table("project_standards") as batch_op:
        batch_op.alter_column("confidence",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=False,
    )
    with op.batch_alter_table("project_standards") as batch_op:
        batch_op.alter_column("confirmed_by",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
        existing_server_default=sa.text("(NULL)"),
    )
    with op.batch_alter_table("project_standards") as batch_op:
        batch_op.alter_column("scanned_at",
        existing_type=sa.TEXT(),
        type_=specweaver.core.config.database.StrictISODateTime(),
        existing_nullable=False,
    )
    op.drop_constraint(None, "project_standards", type_="foreignkey")  # type: ignore[arg-type]
    op.create_foreign_key(
        None, "project_standards", "projects", ["project_name"], ["name"], ondelete="CASCADE"
    )
    with op.batch_alter_table("projects") as batch_op:
        batch_op.alter_column("name", existing_type=sa.TEXT(), type_=sa.String(), nullable=False)
    with op.batch_alter_table("projects") as batch_op:
        batch_op.alter_column("root_path", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False
    )
    with op.batch_alter_table("projects") as batch_op:
        batch_op.alter_column("created_at",
        existing_type=sa.TEXT(),
        type_=specweaver.core.config.database.StrictISODateTime(),
        existing_nullable=False,
    )
    with op.batch_alter_table("projects") as batch_op:
        batch_op.alter_column("last_used_at",
        existing_type=sa.TEXT(),
        type_=specweaver.core.config.database.StrictISODateTime(),
        existing_nullable=False,
    )
    with op.batch_alter_table("projects") as batch_op:
        batch_op.alter_column("log_level",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
        existing_server_default=sa.text("'DEBUG'"),
    )
    with op.batch_alter_table("projects") as batch_op:
        batch_op.alter_column("domain_profile",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
        existing_server_default=sa.text("(NULL)"),
    )
    with op.batch_alter_table("projects") as batch_op:
        batch_op.alter_column("auto_bootstrap_constitution",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
        existing_server_default=sa.text("'prompt'"),
    )
    with op.batch_alter_table("projects") as batch_op:
        batch_op.alter_column("stitch_mode",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
        existing_server_default=sa.text("'off'"),
    )
    with op.batch_alter_table("projects") as batch_op:
        batch_op.alter_column("default_dal",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
        existing_server_default=sa.text("'DAL_A'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projects") as batch_op:
        batch_op.alter_column("default_dal",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
        existing_server_default=sa.text("'DAL_A'"),
    )
    with op.batch_alter_table("projects") as batch_op:
        batch_op.alter_column("stitch_mode",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
        existing_server_default=sa.text("'off'"),
    )
    with op.batch_alter_table("projects") as batch_op:
        batch_op.alter_column("auto_bootstrap_constitution",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
        existing_server_default=sa.text("'prompt'"),
    )
    with op.batch_alter_table("projects") as batch_op:
        batch_op.alter_column("domain_profile",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
        existing_server_default=sa.text("(NULL)"),
    )
    with op.batch_alter_table("projects") as batch_op:
        batch_op.alter_column("log_level",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
        existing_server_default=sa.text("'DEBUG'"),
    )
    with op.batch_alter_table("projects") as batch_op:
        batch_op.alter_column("last_used_at",
        existing_type=specweaver.core.config.database.StrictISODateTime(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    with op.batch_alter_table("projects") as batch_op:
        batch_op.alter_column("created_at",
        existing_type=specweaver.core.config.database.StrictISODateTime(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    with op.batch_alter_table("projects") as batch_op:
        batch_op.alter_column("root_path", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False
    )
    with op.batch_alter_table("projects") as batch_op:
        batch_op.alter_column("name", existing_type=sa.String(), type_=sa.TEXT(), nullable=True)
    op.drop_constraint(None, "project_standards", type_="foreignkey")  # type: ignore[arg-type]
    op.create_foreign_key(None, "project_standards", "projects", ["project_name"], ["name"])
    with op.batch_alter_table("project_standards") as batch_op:
        batch_op.alter_column("scanned_at",
        existing_type=specweaver.core.config.database.StrictISODateTime(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    with op.batch_alter_table("project_standards") as batch_op:
        batch_op.alter_column("confirmed_by",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
        existing_server_default=sa.text("(NULL)"),
    )
    with op.batch_alter_table("project_standards") as batch_op:
        batch_op.alter_column("confidence",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    with op.batch_alter_table("project_standards") as batch_op:
        batch_op.alter_column("data",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    with op.batch_alter_table("project_standards") as batch_op:
        batch_op.alter_column("category",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    with op.batch_alter_table("project_standards") as batch_op:
        batch_op.alter_column("language",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    with op.batch_alter_table("project_standards") as batch_op:
        batch_op.alter_column("scope",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    with op.batch_alter_table("project_standards") as batch_op:
        batch_op.alter_column("project_name",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.create_foreign_key(None, "project_llm_links", "projects", ["project_name"], ["name"])
    with op.batch_alter_table("project_llm_links") as batch_op:
        batch_op.alter_column("role",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    with op.batch_alter_table("project_llm_links") as batch_op:
        batch_op.alter_column("project_name",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_llm_usage_log_task_type"), table_name="llm_usage_log")
    op.drop_index(op.f("ix_llm_usage_log_project_name"), table_name="llm_usage_log")
    op.create_index(op.f("idx_usage_task_type"), "llm_usage_log", ["task_type"], unique=False)
    op.create_index(op.f("idx_usage_project"), "llm_usage_log", ["project_name"], unique=False)
    with op.batch_alter_table("llm_usage_log") as batch_op:
        batch_op.alter_column("run_id",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
        existing_server_default=sa.text("('')"),
    )
    with op.batch_alter_table("llm_usage_log") as batch_op:
        batch_op.alter_column("estimated_cost",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=False,
        existing_server_default=sa.text("(0.0)"),
    )
    with op.batch_alter_table("llm_usage_log") as batch_op:
        batch_op.alter_column("provider",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
        existing_server_default=sa.text("('')"),
    )
    with op.batch_alter_table("llm_usage_log") as batch_op:
        batch_op.alter_column("model",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    with op.batch_alter_table("llm_usage_log") as batch_op:
        batch_op.alter_column("task_type",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    with op.batch_alter_table("llm_usage_log") as batch_op:
        batch_op.alter_column("project_name",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    with op.batch_alter_table("llm_usage_log") as batch_op:
        batch_op.alter_column("timestamp",
        existing_type=specweaver.core.config.database.StrictISODateTime(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    with op.batch_alter_table("llm_usage_log") as batch_op:
        batch_op.alter_column("id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
    )
    with op.batch_alter_table("llm_profiles") as batch_op:
        batch_op.alter_column("provider",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
        existing_server_default=sa.text("'gemini'"),
    )
    with op.batch_alter_table("llm_profiles") as batch_op:
        batch_op.alter_column("response_format",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
        existing_server_default=sa.text("'text'"),
    )
    with op.batch_alter_table("llm_profiles") as batch_op:
        batch_op.alter_column("temperature",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=False,
        existing_server_default=sa.text("(0.7)"),
    )
    with op.batch_alter_table("llm_profiles") as batch_op:
        batch_op.alter_column("model",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
        existing_server_default=sa.text("'gemini-3-flash-preview'"),
    )
    with op.batch_alter_table("llm_profiles") as batch_op:
        batch_op.alter_column("name", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False
    )
    with op.batch_alter_table("llm_profiles") as batch_op:
        batch_op.alter_column("id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
    )
    with op.batch_alter_table("llm_cost_overrides") as batch_op:
        batch_op.alter_column("updated_at",
        existing_type=specweaver.core.config.database.StrictISODateTime(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    with op.batch_alter_table("llm_cost_overrides") as batch_op:
        batch_op.alter_column("output_cost_per_1k",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    with op.batch_alter_table("llm_cost_overrides") as batch_op:
        batch_op.alter_column("input_cost_per_1k",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    with op.batch_alter_table("llm_cost_overrides") as batch_op:
        batch_op.alter_column("model_pattern",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        nullable=True,
    )
    op.drop_index(op.f("ix_artifact_events_parent_id"), table_name="artifact_events")
    op.drop_index(op.f("ix_artifact_events_artifact_id"), table_name="artifact_events")
    op.create_index(op.f("idx_lineage_parent"), "artifact_events", ["parent_id"], unique=False)
    op.create_index(op.f("idx_lineage_artifact"), "artifact_events", ["artifact_id"], unique=False)
    with op.batch_alter_table("artifact_events") as batch_op:
        batch_op.alter_column("model_id",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
        existing_server_default=sa.text("'unknown'"),
    )
    with op.batch_alter_table("artifact_events") as batch_op:
        batch_op.alter_column("timestamp",
        existing_type=specweaver.core.config.database.StrictISODateTime(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    with op.batch_alter_table("artifact_events") as batch_op:
        batch_op.alter_column("event_type",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    with op.batch_alter_table("artifact_events") as batch_op:
        batch_op.alter_column("run_id",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    with op.batch_alter_table("artifact_events") as batch_op:
        batch_op.alter_column("parent_id",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    with op.batch_alter_table("artifact_events") as batch_op:
        batch_op.alter_column("artifact_id",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    with op.batch_alter_table("artifact_events") as batch_op:
        batch_op.alter_column("id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
    )
    with op.batch_alter_table("active_state") as batch_op:
        batch_op.alter_column("value", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False
    )
    with op.batch_alter_table("active_state") as batch_op:
        batch_op.alter_column("key", existing_type=sa.String(), type_=sa.TEXT(), nullable=True
    )
    # ### end Alembic commands ###
