"""Init monolith schema

Revision ID: 037b85034bb0
Revises:
Create Date: 2026-05-02 14:21:41.946055

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import specweaver.core.config.database

# revision identifiers, used by Alembic.
revision: str = '037b85034bb0'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('active_state', 'key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('active_state', 'value',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('artifact_events', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('artifact_events', 'artifact_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('artifact_events', 'parent_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('artifact_events', 'run_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('artifact_events', 'event_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('artifact_events', 'timestamp',
               existing_type=sa.TEXT(),
               type_=specweaver.core.config.database.StrictISODateTime(),
               existing_nullable=False)
    op.alter_column('artifact_events', 'model_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'unknown'"))
    op.drop_index(op.f('idx_lineage_artifact'), table_name='artifact_events')
    op.drop_index(op.f('idx_lineage_parent'), table_name='artifact_events')
    op.create_index(op.f('ix_artifact_events_artifact_id'), 'artifact_events', ['artifact_id'], unique=False)
    op.create_index(op.f('ix_artifact_events_parent_id'), 'artifact_events', ['parent_id'], unique=False)
    op.alter_column('llm_cost_overrides', 'model_pattern',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('llm_cost_overrides', 'input_cost_per_1k',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('llm_cost_overrides', 'output_cost_per_1k',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('llm_cost_overrides', 'updated_at',
               existing_type=sa.TEXT(),
               type_=specweaver.core.config.database.StrictISODateTime(),
               existing_nullable=False)
    op.alter_column('llm_profiles', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('llm_profiles', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('llm_profiles', 'model',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'gemini-3-flash-preview'"))
    op.alter_column('llm_profiles', 'temperature',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.7)'))
    op.alter_column('llm_profiles', 'response_format',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'text'"))
    op.alter_column('llm_profiles', 'provider',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'gemini'"))
    op.alter_column('llm_usage_log', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('llm_usage_log', 'timestamp',
               existing_type=sa.TEXT(),
               type_=specweaver.core.config.database.StrictISODateTime(),
               existing_nullable=False)
    op.alter_column('llm_usage_log', 'project_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('llm_usage_log', 'task_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('llm_usage_log', 'model',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('llm_usage_log', 'provider',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('llm_usage_log', 'estimated_cost',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('llm_usage_log', 'run_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
    op.drop_index(op.f('idx_usage_project'), table_name='llm_usage_log')
    op.drop_index(op.f('idx_usage_task_type'), table_name='llm_usage_log')
    op.create_index(op.f('ix_llm_usage_log_project_name'), 'llm_usage_log', ['project_name'], unique=False)
    op.create_index(op.f('ix_llm_usage_log_task_type'), 'llm_usage_log', ['task_type'], unique=False)
    op.alter_column('project_llm_links', 'project_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('project_llm_links', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(None, 'project_llm_links', type_='foreignkey')  # type: ignore[arg-type]
    op.alter_column('project_standards', 'project_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('project_standards', 'scope',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('project_standards', 'language',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('project_standards', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('project_standards', 'data',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('project_standards', 'confidence',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('project_standards', 'confirmed_by',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('project_standards', 'scanned_at',
               existing_type=sa.TEXT(),
               type_=specweaver.core.config.database.StrictISODateTime(),
               existing_nullable=False)
    op.drop_constraint(None, 'project_standards', type_='foreignkey')  # type: ignore[arg-type]
    op.create_foreign_key(None, 'project_standards', 'projects', ['project_name'], ['name'], ondelete='CASCADE')
    op.alter_column('projects', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('projects', 'root_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('projects', 'created_at',
               existing_type=sa.TEXT(),
               type_=specweaver.core.config.database.StrictISODateTime(),
               existing_nullable=False)
    op.alter_column('projects', 'last_used_at',
               existing_type=sa.TEXT(),
               type_=specweaver.core.config.database.StrictISODateTime(),
               existing_nullable=False)
    op.alter_column('projects', 'log_level',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'DEBUG'"))
    op.alter_column('projects', 'domain_profile',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('projects', 'auto_bootstrap_constitution',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'prompt'"))
    op.alter_column('projects', 'stitch_mode',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'off'"))
    op.alter_column('projects', 'default_dal',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'DAL_A'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'default_dal',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'DAL_A'"))
    op.alter_column('projects', 'stitch_mode',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'off'"))
    op.alter_column('projects', 'auto_bootstrap_constitution',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'prompt'"))
    op.alter_column('projects', 'domain_profile',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('projects', 'log_level',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'DEBUG'"))
    op.alter_column('projects', 'last_used_at',
               existing_type=specweaver.core.config.database.StrictISODateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('projects', 'created_at',
               existing_type=specweaver.core.config.database.StrictISODateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('projects', 'root_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('projects', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_constraint(None, 'project_standards', type_='foreignkey')  # type: ignore[arg-type]
    op.create_foreign_key(None, 'project_standards', 'projects', ['project_name'], ['name'])
    op.alter_column('project_standards', 'scanned_at',
               existing_type=specweaver.core.config.database.StrictISODateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('project_standards', 'confirmed_by',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('project_standards', 'confidence',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('project_standards', 'data',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('project_standards', 'category',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('project_standards', 'language',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('project_standards', 'scope',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('project_standards', 'project_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_foreign_key(None, 'project_llm_links', 'projects', ['project_name'], ['name'])
    op.alter_column('project_llm_links', 'role',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('project_llm_links', 'project_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_llm_usage_log_task_type'), table_name='llm_usage_log')
    op.drop_index(op.f('ix_llm_usage_log_project_name'), table_name='llm_usage_log')
    op.create_index(op.f('idx_usage_task_type'), 'llm_usage_log', ['task_type'], unique=False)
    op.create_index(op.f('idx_usage_project'), 'llm_usage_log', ['project_name'], unique=False)
    op.alter_column('llm_usage_log', 'run_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('llm_usage_log', 'estimated_cost',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('llm_usage_log', 'provider',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('llm_usage_log', 'model',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('llm_usage_log', 'task_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('llm_usage_log', 'project_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('llm_usage_log', 'timestamp',
               existing_type=specweaver.core.config.database.StrictISODateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('llm_usage_log', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('llm_profiles', 'provider',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'gemini'"))
    op.alter_column('llm_profiles', 'response_format',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'text'"))
    op.alter_column('llm_profiles', 'temperature',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.7)'))
    op.alter_column('llm_profiles', 'model',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'gemini-3-flash-preview'"))
    op.alter_column('llm_profiles', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('llm_profiles', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('llm_cost_overrides', 'updated_at',
               existing_type=specweaver.core.config.database.StrictISODateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('llm_cost_overrides', 'output_cost_per_1k',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('llm_cost_overrides', 'input_cost_per_1k',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('llm_cost_overrides', 'model_pattern',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_artifact_events_parent_id'), table_name='artifact_events')
    op.drop_index(op.f('ix_artifact_events_artifact_id'), table_name='artifact_events')
    op.create_index(op.f('idx_lineage_parent'), 'artifact_events', ['parent_id'], unique=False)
    op.create_index(op.f('idx_lineage_artifact'), 'artifact_events', ['artifact_id'], unique=False)
    op.alter_column('artifact_events', 'model_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'unknown'"))
    op.alter_column('artifact_events', 'timestamp',
               existing_type=specweaver.core.config.database.StrictISODateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('artifact_events', 'event_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('artifact_events', 'run_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('artifact_events', 'parent_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('artifact_events', 'artifact_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('artifact_events', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('active_state', 'value',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('active_state', 'key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
