# mypy: ignore-errors
# Copyright (c) 2026 sbula. All rights reserved.
# Licensed under the Apache License, Version 2.0. See LICENSE file in the project root.

"""Integration test: resolver → TelemetryCollector → flush → DB roundtrip.

Verifies that the full telemetry pipeline works end-to-end:
1. The role resolver wraps every adapter it builds in a TelemetryCollector.
2. Calling generate() on the collector records a UsageRecord.
3. Flushing the collector persists records to the Database.
"""

from __future__ import annotations

from typing import TYPE_CHECKING
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from tests.fixtures.db_utils import register_test_project

if TYPE_CHECKING:
    from pathlib import Path


_MACHINE = """\
[servers.gemini]
kind = "gemini"
private = false
max_parallel = 1

[roles]
default = { model = "some-model@gemini", max_output_tokens = 8192 }
"""


class TestTelemetryRoundtrip:
    """Resolver → TelemetryCollector → flush → DB integration test."""

    @pytest.mark.asyncio
    async def test_collector_records_persist_to_db(self, tmp_path: Path):
        """Records generated by TelemetryCollector.flush() appear in the DB."""
        from specweaver.core.config.bootstrap.db_bootstrap import bootstrap_database
        from specweaver.core.config.database import Database
        from specweaver.infrastructure.llm.collector import TelemetryCollector
        from specweaver.infrastructure.llm.models import GenerationConfig, LLMResponse, TokenUsage

        # Set up a real DB
        bootstrap_database(str(tmp_path / ".specweaver-test" / "specweaver.db"))
        db = Database(tmp_path / ".specweaver-test" / "specweaver.db")
        register_test_project(db, "testproj", ".")

        # Create a collector wrapping a mock adapter
        mock_adapter = MagicMock()
        mock_adapter.provider_name = "test-provider"
        mock_adapter.generate = AsyncMock(
            return_value=LLMResponse(
                text="hello",
                model="test-model",
                usage=TokenUsage(
                    prompt_tokens=100,
                    completion_tokens=50,
                    total_tokens=150,
                ),
            )
        )

        collector = TelemetryCollector(mock_adapter, "testproj")

        # Call generate — should capture one record
        config = GenerationConfig(model="test-model", temperature=0.7, run_id="mock-run-id-123")
        await collector.generate([], config)

        assert len(collector.records) == 1
        assert collector.records[0].run_id == "mock-run-id-123"

        # Flush to DB
        count = collector.flush(db)

        assert count == 1
        assert len(collector.records) == 0  # Records cleared after flush

        # Verify records are in the DB

        from specweaver.infrastructure.llm.store import LlmRepository

        async with db.async_session_scope() as session:
            rows = await LlmRepository(session).get_usage_summary("testproj")

        assert len(rows) == 1
        assert rows[0]["total_tokens"] == 150
        assert rows[0]["call_count"] == 1

        with db.connect() as conn:
            cursor = conn.execute(
                "SELECT run_id FROM llm_usage_log WHERE project_name = 'testproj'"
            )
            row = cursor.fetchone()
            assert row is not None
            assert row["run_id"] == "mock-run-id-123"

    def test_the_resolver_builds_a_collector_for_the_project(self, tmp_path: Path):
        """Every adapter a command's router hands out records usage against its project."""
        from specweaver.core.config.llm_settings import LlmSettingsFiles
        from specweaver.infrastructure.llm.collector import TelemetryCollector
        from specweaver.infrastructure.llm.models import TaskType
        from specweaver.infrastructure.llm.router import build_router

        files = LlmSettingsFiles.from_texts(
            machine_text=_MACHINE, machine_source="-", project_text="", project_source="-"
        )
        with patch.dict("os.environ", {"GEMINI_API_KEY": "test-key"}):
            router = build_router(
                files,
                project="testproj",
                roles=[TaskType.DRAFT],
                spend_limit_usd=None,
                token_limit=None,
            )
            adapter = router.get_for_task(TaskType.DRAFT).adapter

        assert isinstance(adapter, TelemetryCollector)
        assert adapter._project == "testproj"
