# Copyright (c) 2026 sbula. All rights reserved.
# Licensed under the MIT License. See LICENSE file in the project root.

"""Integration test: factory → TelemetryCollector → flush → DB roundtrip.

Verifies that the full telemetry pipeline works end-to-end:
1. Factory creates a TelemetryCollector wrapper when telemetry_project is set.
2. Calling generate() on the collector records a UsageRecord.
3. Flushing the collector persists records to the Database.
"""

from __future__ import annotations

from typing import TYPE_CHECKING
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

if TYPE_CHECKING:
    from pathlib import Path


class TestTelemetryRoundtrip:
    """Factory → TelemetryCollector → flush → DB integration test."""

    @pytest.mark.asyncio
    async def test_collector_records_persist_to_db(self, tmp_path: Path):
        """Records generated by TelemetryCollector.flush() appear in the DB."""
        from specweaver.config.database import Database
        from specweaver.llm.collector import TelemetryCollector
        from specweaver.llm.models import GenerationConfig, LLMResponse, TokenUsage

        # Set up a real DB
        db = Database(tmp_path / ".specweaver-test" / "specweaver.db")
        db.register_project("testproj", ".")

        # Create a collector wrapping a mock adapter
        mock_adapter = MagicMock()
        mock_adapter.provider_name = "test-provider"
        mock_adapter.generate = AsyncMock(
            return_value=LLMResponse(
                text="hello",
                model="test-model",
                usage=TokenUsage(
                    prompt_tokens=100,
                    completion_tokens=50,
                    total_tokens=150,
                ),
            )
        )

        collector = TelemetryCollector(mock_adapter, "testproj")

        # Call generate — should capture one record
        config = GenerationConfig(model="test-model", temperature=0.7, run_id="mock-run-id-123")
        await collector.generate([], config)

        assert len(collector.records) == 1
        assert collector.records[0].run_id == "mock-run-id-123"

        # Flush to DB
        count = collector.flush(db)

        assert count == 1
        assert len(collector.records) == 0  # Records cleared after flush

        # Verify records are in the DB
        rows = db.get_usage_summary(project="testproj")
        assert len(rows) == 1
        assert rows[0]["total_tokens"] == 150
        assert rows[0]["call_count"] == 1

        with db.connect() as conn:
            cursor = conn.execute(
                "SELECT run_id FROM llm_usage_log WHERE project_name = 'testproj'"
            )
            row = cursor.fetchone()
            assert row is not None
            assert row["run_id"] == "mock-run-id-123"

    @pytest.mark.asyncio
    async def test_factory_creates_collector_when_project_set(self, tmp_path: Path):
        """create_llm_adapter wraps in TelemetryCollector when telemetry_project is set."""
        from specweaver.config.database import Database
        from specweaver.llm.collector import TelemetryCollector

        db = Database(tmp_path / ".specweaver-test" / "specweaver.db")
        db.register_project("testproj", ".")
        db.set_active_project("testproj")

        with patch.dict("os.environ", {"GEMINI_API_KEY": "test-key"}):
            from specweaver.llm.factory import create_llm_adapter

            _settings, adapter, _config = create_llm_adapter(
                db,
                telemetry_project="testproj",
            )

        assert isinstance(adapter, TelemetryCollector)

    @pytest.mark.asyncio
    async def test_factory_returns_plain_adapter_when_no_project(self, tmp_path: Path):
        """create_llm_adapter returns plain adapter when telemetry_project is None."""
        from specweaver.config.database import Database
        from specweaver.llm.collector import TelemetryCollector

        db = Database(tmp_path / ".specweaver-test" / "specweaver.db")
        db.register_project("testproj", ".")
        db.set_active_project("testproj")

        with patch.dict("os.environ", {"GEMINI_API_KEY": "test-key"}):
            from specweaver.llm.factory import create_llm_adapter

            _settings, adapter, _config = create_llm_adapter(
                db,
                telemetry_project=None,
            )

        assert not isinstance(adapter, TelemetryCollector)
