# Copyright (c) 2026 sbula. All rights reserved.
# Licensed under the MIT License. See LICENSE file in the project root.

"""Integration tests — sw scan + context inference on real directories.

Exercises ContextInferrer against the sample project fixture and custom
temp directories to verify auto-generated context.yaml content.

Uses the shared ``sample_project`` fixture for the ``no_context`` module.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from specweaver.context.inferrer import ContextInferrer

if TYPE_CHECKING:
    from pathlib import Path

# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


class TestContextInferenceFixture:
    """ContextInferrer on the sample project's no_context module."""

    def test_infer_from_fixture_module(self, sample_project: Path) -> None:
        """no_context module → generates context.yaml with correct fields."""
        mod_dir = sample_project / "src" / "no_context"

        inferrer = ContextInferrer()
        result = inferrer.infer_and_write(mod_dir)

        assert result.was_generated is True
        assert result.node is not None
        assert result.node.name == "no_context"
        # Docstring says "Data processing pipeline"
        assert "data" in result.node.purpose.lower() or "processing" in result.node.purpose.lower()

        # context.yaml was written
        ctx_file = mod_dir / "context.yaml"
        assert ctx_file.exists()
        content = ctx_file.read_text(encoding="utf-8")
        assert "AUTO-GENERATED" in content

    def test_infer_public_symbols_from_fixture(self, sample_project: Path) -> None:
        """no_context module → public symbols detected, private excluded."""
        mod_dir = sample_project / "src" / "no_context"

        inferrer = ContextInferrer()
        result = inferrer.infer_and_write(mod_dir)

        assert result.was_generated is True
        assert "Record" in result.node.exposes
        assert "RecordProcessor" in result.node.exposes
        assert "summarize" in result.node.exposes
        assert "_internal_helper" not in result.node.exposes

    def test_fixture_greeter_has_no_context_yaml(self, sample_project: Path) -> None:
        """greeter module has no context.yaml → can be inferred."""
        mod_dir = sample_project / "src" / "greeter"

        # Remove context.yaml if it was already generated by another test
        ctx_file = mod_dir / "context.yaml"
        if ctx_file.exists():
            ctx_file.unlink()

        inferrer = ContextInferrer()
        result = inferrer.infer_and_write(mod_dir)

        assert result.was_generated is True
        assert "Greeter" in result.node.exposes
        assert "format_greeting" in result.node.exposes


class TestContextInferenceEdgeCases:
    """Edge cases with custom inline directories."""

    def test_skip_existing_context_yaml(self, tmp_path: Path) -> None:
        """Directory with existing context.yaml → skipped, not overwritten."""
        mod_dir = tmp_path / "existing"
        mod_dir.mkdir()

        (mod_dir / "__init__.py").write_text('"""Module."""\n', encoding="utf-8")
        existing = mod_dir / "context.yaml"
        existing.write_text("name: existing\n", encoding="utf-8")

        inferrer = ContextInferrer()
        result = inferrer.infer_and_write(mod_dir)

        assert result.was_generated is False
        assert existing.read_text(encoding="utf-8") == "name: existing\n"

    def test_skip_non_python_directory(self, tmp_path: Path) -> None:
        """Directory with no Python files → skipped."""
        mod_dir = tmp_path / "static"
        mod_dir.mkdir()
        (mod_dir / "readme.md").write_text("# readme\n", encoding="utf-8")

        inferrer = ContextInferrer()
        result = inferrer.infer_and_write(mod_dir)

        assert result.was_generated is False
        assert not (mod_dir / "context.yaml").exists()

    def test_infer_archetype_adapter(self, tmp_path: Path) -> None:
        """Module importing external packages → archetype = adapter."""
        mod_dir = tmp_path / "adapter_mod"
        mod_dir.mkdir()

        (mod_dir / "__init__.py").write_text(
            '"""External adapter."""\n',
            encoding="utf-8",
        )
        (mod_dir / "client.py").write_text(
            "import requests\n\nclass APIClient:\n    pass\n",
            encoding="utf-8",
        )

        inferrer = ContextInferrer()
        result = inferrer.infer_and_write(mod_dir)

        assert result.was_generated is True
        assert result.node.archetype == "adapter"

    def test_infer_archetype_pure_logic(self, tmp_path: Path) -> None:
        """Module with only stdlib imports → archetype = pure-logic."""
        mod_dir = tmp_path / "core"
        mod_dir.mkdir()

        (mod_dir / "__init__.py").write_text(
            '"""Core logic."""\n',
            encoding="utf-8",
        )
        (mod_dir / "logic.py").write_text(
            "import json\nfrom pathlib import Path\n\ndef process() -> dict:\n    return {}\n",
            encoding="utf-8",
        )

        inferrer = ContextInferrer()
        result = inferrer.infer_and_write(mod_dir)

        assert result.was_generated is True
        assert result.node.archetype == "pure-logic"

    def test_infer_public_symbols_from_all(self, tmp_path: Path) -> None:
        """Module with __all__ → exposes matches __all__ exactly."""
        mod_dir = tmp_path / "api"
        mod_dir.mkdir()

        (mod_dir / "__init__.py").write_text(
            '"""Public API."""\n\n__all__ = ["Client", "Config"]\n',
            encoding="utf-8",
        )
        (mod_dir / "client.py").write_text(
            "class Client:\n    pass\n\nclass _InternalHelper:\n    pass\n",
            encoding="utf-8",
        )

        inferrer = ContextInferrer()
        result = inferrer.infer_and_write(mod_dir)

        assert result.was_generated is True
        assert "Client" in result.node.exposes
        assert "Config" in result.node.exposes
        assert "_InternalHelper" not in result.node.exposes
