# Copyright (c) 2026 sbula. All rights reserved.
# Licensed under the MIT License. See LICENSE file in the project root.

"""Planning models — structured output for the plan step.

These Pydantic models define the machine-readable Plan artifact that
bridges spec validation/review and code generation:

- ``FileChange``: a single file to create, modify, or delete.
- ``ArchitectureSection``: module layout, dependency direction, archetype.
- ``TechStackChoice``: technology choice with rationale.
- ``ConstraintNote``: constraint extracted from the spec.
- ``ImplementationTask``: an ordered implementation step.
- ``TestExpectation``: lightweight test scenario hint (precursor to 3.17).
- ``MockupReference``: UI mockup reference from Stitch (3.6b).
- ``PlanArtifact``: the complete plan with mandatory + optional sections.

The Plan is stored as YAML (primary, machine-first) with optional
Markdown rendering on request. Agents consume the YAML directly;
HITL reviews use the rendered Markdown when needed.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

# Known archetypes from SpecWeaver's context.yaml convention.
# Unknown archetypes produce a warning, not a hard error.
KNOWN_ARCHETYPES: frozenset[str] = frozenset(
    {"adapter", "orchestrator", "pure-logic", "leaf", "data"}
)


class FileChange(BaseModel):
    """A single file to create, modify, or delete.

    Attributes:
        path: Relative path within the project (e.g. ``src/auth/login.py``).
        action: One of ``create``, ``modify``, ``delete``.
        purpose: Why this file is needed.
        dependencies: Other file paths that must exist before this one.
    """

    path: str
    action: Literal["create", "modify", "delete"]
    purpose: str
    dependencies: list[str] = Field(default_factory=list)


class ArchitectureSection(BaseModel):
    """Architecture decisions for the Plan.

    Attributes:
        module_layout: Description of module/package organization.
        dependency_direction: How dependencies flow (e.g. ``downward``).
        archetype: Module archetype. Free-form string; warn if not in
            :data:`KNOWN_ARCHETYPES`.
        patterns: Design patterns applied (e.g. ``["strategy", "factory"]``).
    """

    module_layout: str
    dependency_direction: str
    archetype: str  # free-form; warn if not in KNOWN_ARCHETYPES
    patterns: list[str] = Field(default_factory=list)


class TechStackChoice(BaseModel):
    """A technology choice with rationale.

    Attributes:
        category: What kind of choice (e.g. ``http client``, ``ORM``).
        choice: The chosen technology.
        rationale: Why this was chosen over alternatives.
        alternatives_considered: Other options evaluated.
    """

    category: str
    choice: str
    rationale: str
    alternatives_considered: list[str] = Field(default_factory=list)


class ConstraintNote(BaseModel):
    """A constraint extracted from the spec.

    Attributes:
        source: Where in the spec this constraint was found (e.g. ``§ Boundaries``).
        constraint: The constraint itself.
        impact: How this constraint affects the implementation.
    """

    source: str
    constraint: str
    impact: str


class ImplementationTask(BaseModel):
    """An ordered implementation step.

    Attributes:
        name: Short task name.
        description: What to do in this step.
        files: Which files this task touches.
        dependencies: Task names that must complete first.
    """

    name: str
    description: str
    files: list[str]
    dependencies: list[str] = Field(default_factory=list)


class TestExpectation(BaseModel):
    """A lightweight test scenario hint (precursor to full 3.17 scenarios).

    Attributes:
        name: Identifier (e.g. ``happy_path_login``).
        description: What the test checks.
        function_under_test: Function/method name being tested.
        input_summary: Brief description of inputs.
        expected_behavior: What should happen.
        category: One of ``happy``, ``error``, ``boundary``.
    """

    __test__ = False  # Prevent pytest from collecting this Pydantic model

    name: str
    description: str
    function_under_test: str
    input_summary: str
    expected_behavior: str
    category: Literal["happy", "error", "boundary"] = "happy"


class MockupReference(BaseModel):
    """Reference to a UI mockup generated by Stitch (3.6b).

    Attributes:
        screen_name: Name of the UI screen.
        description: What the mockup shows.
        preview_url: Stitch preview URL for interactive viewing.
    """

    screen_name: str
    description: str
    preview_url: str


class PlanArtifact(BaseModel):
    """Complete implementation plan for a spec.

    Mandatory fields define the core deliverable: *which spec*,
    *which files to create*, and *when*. Everything else is enrichment.

    Attributes:
        spec_path: Path to the source spec.
        spec_name: Human-readable spec name.
        spec_hash: SHA-256 hash of spec content for staleness detection.
        file_layout: Concrete files to create/modify/delete.
        timestamp: ISO-8601 creation timestamp.
        architecture: Module layout, dependency direction, archetype.
        tech_stack: Technology choices with rationale.
        constraints: Non-functional constraints from the spec.
        tasks: Ordered implementation steps.
        test_expectations: Lightweight test scenario hints.
        mockups: UI mockup references (populated by Stitch in 3.6b).
        reasoning: LLM chain-of-thought (stored in YAML, omitted from Markdown).
        confidence: LLM confidence score (0-100).
    """

    # === MANDATORY ===
    spec_path: str
    spec_name: str
    spec_hash: str
    file_layout: list[FileChange]
    timestamp: str

    # === OPTIONAL ===
    architecture: ArchitectureSection | None = None
    tech_stack: list[TechStackChoice] = Field(default_factory=list)
    constraints: list[ConstraintNote] = Field(default_factory=list)
    tasks: list[ImplementationTask] = Field(default_factory=list)
    test_expectations: list[TestExpectation] = Field(default_factory=list)
    mockups: list[MockupReference] = Field(default_factory=list)
    reasoning: str = ""
    confidence: int = 0
