#!/usr/bin/env python3
# Copyright (c) 2026 sbula. All rights reserved.
# Licensed under the Apache License, Version 2.0. See LICENSE file in the project root.

"""Regenerate the half of a handover that a script can know, and never touch the other half.

A handover carries two kinds of thing, and they fail in opposite directions.

**State** — suite result, gate status, open contract rows, how far ahead of origin. All computable,
and all of it goes stale precisely *because* it is written by hand: the numbers are copied at the
moment someone remembers to, and then quietly describe a repo that has moved. Advising prose
discipline for a number a script can compute is how it drifts.

**Lossy facts** — a decision now waiting on a human, an approach measured and rejected, an analysis
that must be read before touching something. Nothing derives these. They exist only if someone writes
them at the moment they happen, which is what the `specweaver-pre-commit`, `specweaver-design` and
`specweaver-ticket` skills now prompt for.

So this owns the first kind and is forbidden the second. Everything between the markers is rewritten
on every run; everything outside is returned byte-for-byte. `E-VAL-03` survived across sessions only
because a handover paragraph said *do not restart the research* — a generator that can eat that
paragraph is worth less than no generator.

    python scripts/session_handover.py            # fast facts: git, registries, sweeps
    python scripts/session_handover.py --gates    # also run quality.py cb + doc
    python scripts/session_handover.py --suite    # also run the full suite (~75s) for the real count
    python scripts/session_handover.py --show     # print, write nothing
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
HANDOVER = REPO_ROOT / ".tmp" / "HANDOVER.md"
CONTRACTS = REPO_ROOT / "docs" / "roadmap" / "stories"
ROADMAP = REPO_ROOT / "docs" / "roadmap" / "master_story_roadmap.md"
MIGRATION_LEDGER = (
    REPO_ROOT
    / "docs"
    / "roadmap"
    / "features"
    / "topic_07_technical_debt"
    / "TECH-060"
    / "TECH-060_delivery.md"
)

#: Everything between these is generated. They are HTML comments so they render as nothing.
BEGIN = "<!-- handover:state:begin — generated by scripts/session_handover.py, do not edit -->"
END = "<!-- handover:state:end -->"

#: A blocker cell naming a registry ID is waiting on someone else. One saying "none — needs a test"
#: is actionable now, and the difference is the single most useful thing in the row.
_BLOCKER_ID = re.compile(r"[A-E]-[A-Z]{2,}-\d+|TECH-\d{3}|US-\d+")


class HandoverError(RuntimeError):
    """The existing file is not in a shape this can safely rewrite."""


@dataclass(frozen=True)
class OpenRow:
    story: str
    number: str
    path: str
    blocker: str
    blocked_externally: bool


# --- pure parsing -------------------------------------------------------------------------------


def _cells(line: str) -> list[str]:
    return [c.strip() for c in line.strip().strip("|").split("|")]


def migration_counts(roadmap_text: str) -> dict[str, int]:
    """Discharged / open / held rows in the `-MIG` ledger.

    The ledger spans two documents — open rows on the roadmap, discharged rows in `TECH-060`'s
    delivery record — so callers pass both texts and this counts whatever it is given.
    """
    counts = {"discharged": 0, "open": 0, "held": 0}
    for line in roadmap_text.splitlines():
        if "-MIG`" not in line or not line.strip().startswith("|"):
            continue
        if "`✅`" in line:
            counts["discharged"] += 1
        elif "`🔵`" in line:
            counts["held"] += 1
        elif "`[ ]`" in line:
            counts["open"] += 1
    return counts


def open_rows(contract_text: str, story: str) -> list[OpenRow]:
    """Path-inventory rows whose `Runnable today` column says no."""
    rows: list[OpenRow] = []
    for line in contract_text.splitlines():
        s = line.strip()
        if not s.startswith("|") or s.startswith("|---") or "| # |" in s:
            continue
        cells = _cells(s)
        if len(cells) != 6 or not cells[4].lower().startswith("no"):
            continue
        rows.append(
            OpenRow(
                story=story,
                number=cells[0],
                path=cells[1],
                blocker=cells[5],
                blocked_externally=bool(_BLOCKER_ID.search(cells[3] + " " + cells[5])),
            )
        )
    return rows


#: A blocker cell that names a *decision* is the user's to answer; one that names none at all is an
#: agent's to go and do. The cell already carries the distinction, so nothing has to be inferred.
_DECISION = re.compile(r"\bdecision\b", re.I)


def awaiting_decision(rows: list[OpenRow]) -> list[OpenRow]:
    """Open rows whose blocker is a judgement only the user can make."""
    return [r for r in rows if not r.blocked_externally and _DECISION.search(r.blocker)]


def awaiting_work(rows: list[OpenRow]) -> list[OpenRow]:
    """Open rows with no external blocker and no decision pending — someone can just write the test."""
    return [r for r in rows if not r.blocked_externally and not _DECISION.search(r.blocker)]


def render_needs_you(*, unpushed: int, dirty: int, rows: list[OpenRow], handover_text: str) -> str:
    """The section that says what cannot proceed without the user.

    Deliberately explicit about its own blind spot. A HITL gate a skill stopped at is not derivable
    from any artefact, so an empty list here means *nothing was recorded*, never *nothing is pending* —
    and saying which is the difference between a useful section and a misleading one.
    """
    out = ["### Needs you", ""]

    if unpushed:
        out.append(
            f"- **{unpushed} commit(s) unpushed.** `git push` is not in this repo's Bash allow-list, "
            "so it is always yours to run: `git push origin main`"
        )
    if dirty:
        out.append(f"- **{dirty} file(s) uncommitted** — decide whether they belong in a commit")

    decisions = awaiting_decision(rows)
    if decisions:
        out.append(
            f"- **{len(decisions)} contract row(s) waiting on a judgement only you can make:**"
        )
        out += [f"  - `{r.story}` {r.number} — {r.blocker}" for r in decisions]

    work = awaiting_work(rows)
    if work:
        out.append(
            f"- {len(work)} row(s) need a test rather than a decision — an agent can take these "
            "without asking:"
        )
        out += [f"  - `{r.story}` {r.number} — {r.blocker}" for r in work]

    if "*(none recorded" in handover_text or not handover_text.strip():
        out += [
            "",
            "> **A HITL gate is not derivable from any artefact.** The sections above this block are "
            "empty or stubbed, which means *nothing was recorded* — not that nothing is pending. If a "
            "skill stopped at a gate this session, write it there before the session ends.",
        ]

    if len(out) == 2:
        out.append(
            "*Nothing derivable is waiting. Check the recorded sections above — a HITL gate is not "
            "derivable and appears there only if someone wrote it down.*"
        )
    return "\n".join(out)


def _all_open_rows() -> list[OpenRow]:
    """Every open inventory row across every contract that has one."""
    if not CONTRACTS.is_dir():
        return []
    return [
        r
        for f in sorted(CONTRACTS.glob("US-*.md"))
        for r in open_rows(f.read_text(encoding="utf-8"), f.stem)
    ]


def splice(existing: str, block: str) -> str:
    """Replace the generated block, returning everything else unchanged.

    With no markers the block is inserted after the title, so an older handover gains the section
    without losing a word of itself.
    """
    generated = f"{BEGIN}\n{block.rstrip()}\n{END}"

    has_begin, has_end = BEGIN in existing, END in existing
    if has_begin != has_end:
        raise HandoverError(
            "unterminated generated block — the file has one marker and not the other. Fix it by "
            "hand; rewriting over it would destroy whatever sits below the opening marker."
        )

    if has_begin:
        head, rest = existing.split(BEGIN, 1)
        _, tail = rest.split(END, 1)
        return head + generated + tail

    lines = existing.splitlines()
    at = 1 if lines and lines[0].startswith("# ") else 0
    head, tail = lines[:at], lines[at:]
    # Trim the blank lines either side of the seam, so inserting the block adds exactly one separator
    # rather than stacking onto whatever spacing the file already had.
    while tail and not tail[0].strip():
        tail.pop(0)
    while head and not head[-1].strip():
        head.pop()
    return "\n".join([*head, "", generated, "", *tail]).lstrip("\n") + "\n"


# --- gathering ----------------------------------------------------------------------------------


def _run(*cmd: str, timeout: int = 900) -> tuple[int, str]:
    try:
        # `scripts/**` is exempt from the SubprocessExecutor rule: a repo tool that reports on the
        # repo must not import the product it describes, or it cannot run when that product is broken.
        p = subprocess.run(cmd, cwd=REPO_ROOT, capture_output=True, text=True, timeout=timeout)
    except (OSError, subprocess.TimeoutExpired) as exc:
        return 1, f"({cmd[0]} unavailable: {exc})"
    return p.returncode, (p.stdout + p.stderr).strip()


def _git_state() -> list[str]:
    _, branch = _run("git", "rev-parse", "--abbrev-ref", "HEAD")
    _, ahead = _run("git", "rev-list", "--count", "@{u}..HEAD")
    _, dirty = _run("git", "status", "--porcelain")
    n_dirty = len([x for x in dirty.splitlines() if x.strip()])
    tree = "clean" if n_dirty == 0 else f"**{n_dirty} file(s) uncommitted**"
    unpushed = f"**{ahead} unpushed**" if ahead.isdigit() and int(ahead) else "nothing unpushed"
    return [f"- **Git** `{branch}`, {unpushed}, working tree {tree}"]


def _sweeps() -> list[str]:
    sys.path.insert(0, str(REPO_ROOT / "scripts"))
    out = []
    for name, label in (("check_fr_sweep", "FR"), ("check_nfr_sweep", "NFR")):
        try:
            mod = __import__(name)
            census = mod.census()
            out.append(f"{label} {sum(census.values())} uncited across {len(census)} design(s)")
        except Exception as exc:  # a sweep that cannot run is worth saying, not worth failing on
            out.append(f"{label} unavailable ({type(exc).__name__})")
    return [f"- **Sweeps** {'; '.join(out)}"]


def _registries() -> list[str]:
    lines: list[str] = []
    if ROADMAP.is_file():
        # The roadmap quotes the rows still open; the discharged ones are read from the ledger.
        ledger = MIGRATION_LEDGER.read_text(encoding="utf-8") if MIGRATION_LEDGER.is_file() else ""
        c = migration_counts(ROADMAP.read_text(encoding="utf-8") + ledger)
        total = sum(c.values())
        lines.append(
            f"- **Migration** {c['discharged']}/{total} rows discharged, "
            f"{c['open']} open, {c['held']} held"
        )
    rows = [
        r
        for f in sorted(CONTRACTS.glob("US-*.md"))
        for r in open_rows(f.read_text(encoding="utf-8"), f.stem)
    ]
    if rows:
        actionable = [r for r in rows if not r.blocked_externally]
        contracts = len({r.story for r in rows})
        lines.append(
            f"- **Open contract rows** {len(rows)} across {contracts} contract(s) — "
            f"{len(rows) - len(actionable)} waiting on named work, "
            f"**{len(actionable)} with no external blocker**"
        )
    return lines


def _optional(gates: bool, suite: bool) -> list[str]:
    lines: list[str] = []
    if gates:
        for gate in ("cb", "doc"):
            code, out = _run(sys.executable, "scripts/quality.py", gate)
            tail = next((x for x in reversed(out.splitlines()) if "of" in x and "checks" in x), "?")
            lines.append(
                f"- **Gate `{gate}`** {'green' if code == 0 else '**RED**'} — {tail.strip()}"
            )
    if suite:
        code, out = _run(sys.executable, "-m", "pytest", "-n", "auto", "-q", "--tb=no")
        tail = next((x for x in reversed(out.splitlines()) if "passed" in x or "failed" in x), "?")
        lines.append(f"- **Suite** {'green' if code == 0 else '**RED**'} — {tail.strip()}")
    else:
        lines.append("- **Suite** not measured in this run — `--suite` to measure it")
    return lines


def render_state(*, gates: bool = False, suite: bool = False) -> str:
    stamp = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    body = [
        "## State",
        "",
        f"*Generated {stamp}. Everything in this section is derived; edit above or below it.*",
        "",
    ]
    body += _git_state() + _optional(gates, suite) + _registries() + _sweeps()

    existing = HANDOVER.read_text(encoding="utf-8") if HANDOVER.is_file() else ""
    _, ahead = _run("git", "rev-list", "--count", "@{u}..HEAD")
    _, dirty = _run("git", "status", "--porcelain")
    body += [
        "",
        render_needs_you(
            unpushed=int(ahead) if ahead.isdigit() else 0,
            dirty=len([x for x in dirty.splitlines() if x.strip()]),
            rows=_all_open_rows(),
            handover_text=existing,
        ),
    ]
    _, log = _run("git", "log", "--oneline", "-8")
    body += [
        "",
        "<details><summary>Last 8 commits</summary>",
        "",
        "```",
        log,
        "```",
        "",
        "</details>",
    ]
    return "\n".join(body)


TEMPLATE = """# Handover

**First: read [`docs/dev_guides/working_in_this_repo.md`](../docs/dev_guides/working_in_this_repo.md).**
Delete this file when done; it is gitignored, so it never leaves this machine.

## Decisions waiting on the user

*(none recorded — a skill should have written any HITL gate it stopped at)*

## Tried and rejected — do not repeat

*(none recorded)*

## Read before touching

*(none recorded — link any `docs/analysis/` document produced this session)*
"""


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--gates", action="store_true", help="also run quality.py cb and doc")
    ap.add_argument("--suite", action="store_true", help="also run the full suite (~75s)")
    ap.add_argument("--show", action="store_true", help="print the state block; write nothing")
    args = ap.parse_args(argv)

    block = render_state(gates=args.gates, suite=args.suite)
    if args.show:
        print(block)
        return 0

    existing = HANDOVER.read_text(encoding="utf-8") if HANDOVER.is_file() else TEMPLATE
    try:
        updated = splice(existing, block)
    except HandoverError as exc:
        print(f"handover: {exc}", file=sys.stderr)
        return 1

    HANDOVER.parent.mkdir(parents=True, exist_ok=True)
    HANDOVER.write_text(updated, encoding="utf-8")
    verb = "updated" if existing is not TEMPLATE else "created"
    print(f"handover {verb}: {HANDOVER.relative_to(REPO_ROOT)}")
    print("  the human sections were not touched — fill them in yourself")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
