# Copyright (c) 2026 sbula. All rights reserved.
# Licensed under the Apache License, Version 2.0. See LICENSE file in the project root.

"""Integration test ensuring ConvertScenarioHandler executes polyglot routing accurately."""

from __future__ import annotations

from pathlib import Path
from unittest.mock import MagicMock

import pytest

from specweaver.core.flow.handlers import RunContext
from specweaver.core.flow.handlers.scenario import ConvertScenarioHandler

pytestmark = pytest.mark.integration


@pytest.mark.asyncio()
@pytest.mark.parametrize(
    "indicator_file, expected_test_file",
    [
        ("pyproject.toml", "scenarios/generated/test_auth_scenarios.py"),
        ("pom.xml", "src/test/java/scenarios/generated/AuthScenariosTest.java"),
        ("build.gradle", "src/test/kotlin/scenarios/generated/AuthScenariosTest.kt"),
        ("package.json", "scenarios/generated/auth.scenarios.test.ts"),
        ("Cargo.toml", "tests/auth_scenarios.rs"),
    ],
)
async def test_polyglot_scenario_generation_integration(
    tmp_path: Path, indicator_file: str, expected_test_file: str
) -> None:
    """Verifies that the ConvertScenarioHandler inherently routes to the correct ScenarioConverter
    based on the project structure and writes the correctly formatted framework path.
    """
    (tmp_path / indicator_file).write_text("dummy", encoding="utf-8")

    # The scenario_yaml produced by GenerateScenarioHandler
    scenarios_dir = tmp_path / "scenarios" / "definitions"
    scenarios_dir.mkdir(parents=True, exist_ok=True)
    scenario_yaml_path = scenarios_dir / "auth_scenarios.yaml"

    yaml_data = """
spec_path: specs/auth_spec.md
contract_path: contracts/auth_contract.py
scenarios:
  - name: test_valid_login
    description: Happy path
    function_under_test: login
    req_id: FR-1
    category: happy
"""
    scenario_yaml_path.write_text(yaml_data, encoding="utf-8")

    ctx = MagicMock(spec=RunContext)
    ctx.project_path = tmp_path
    ctx.spec_path = Path("specs/auth_spec.md")
    # Emulate the feedback context generated by GenerateScenarioHandler
    ctx.feedback = {"scenario_yaml_path": str(scenario_yaml_path)}

    from specweaver.core.flow.engine.models import PipelineStep

    step = PipelineStep(name="test", action="convert", target="scenario")

    handler = ConvertScenarioHandler()
    result = await handler.execute(step, ctx)

    from specweaver.core.flow.engine.state import StepResult

    assert type(result) is StepResult
    if result.status.value != "passed":
        print(f"ERROR: {result.error_message}")
        print(f"CTX_FEEDBACK: {ctx.feedback}")
    assert result.status.value == "passed"

    # Validate physical write bounds
    generated_path = tmp_path / expected_test_file
    assert generated_path.exists(), f"Framework file missing at expected path: {generated_path}"
    content = generated_path.read_text(encoding="utf-8")

    # Ensure traces exist
    assert "FR-1" in content
    # Ensure the function name exists
    assert "login" in content.lower()
